Repository Team-TTT/Circle-Service-FE, pull requests merged in 2022-10, with the labels that each got.

#1 docs: pr 관련 파일 생성
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: docs, review-required

#4 [2022.10.22] feat: home page
  .eslintrc.js
  .github/pull_request_template.md
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/GlobalStyle.js
  src/app/App.js
  src/config/constants/theme.js
  src/index.js
  src/layout/ServiceLayOut/index.js
  src/pages/ChannelPage/index.js
  src/pages/Homepage/index.js
Labels: feat, review-required

#5 feat: 채널방룸 simple-peer와 webRTC를 이용한 실시간 미디어통신 구현 완료
  .env.sample
  package-lock.json
  package.json
  src/GlobalStyle.js
  src/app/App.js
  src/components/Channel/AudioContainer.js
  src/components/Channel/CalleeAudio.js
  src/components/common/Header.js
  src/components/shared/AudioWrapper.js
  src/components/shared/LoadingUserIcon.js
  src/components/shared/StyledAudio.js
  src/components/shared/UserIcon.js
  src/config/constants/index.js
  src/hooks/useConnection.js
  src/hooks/useSocket.js
  src/index.js
  src/layout/ServiceLayOut/index.js
  src/pages/ChannelPage/index.js
  src/pages/ErrorPage/index.js
  src/pages/Homepage/index.js
  src/reducer/actions.js
  src/reducer/index.js
  src/util/handleStream.js
  src/util/socketFactory.js
Labels: feat, review-required

#8 refactor: socket 경로 추가
  package.json
  src/util/socketFactory.js
Labels: refactor, review-required

#9 feat: 종료버튼 tooltip 메세지 표현 기능 구현
  src/components/common/CloseTooltip.js
  src/layout/ServiceLayOut/Header.js
  src/pages/ChannelPage/index.js
Labels: feat, review-required

#7 [2022.10.26] feat: 부모 html에서 자식 iframe 사이 데이터 주고 받고 함수 실행시키기
  .env.sample
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  public/index.html
  src/GlobalStyle.js
  src/components/Channel/CalleeAudio.js
  src/hooks/useConnection.js
  src/index.js
  src/layout/ServiceLayOut/Header.js
  src/layout/ServiceLayOut/index.js
  src/pages/Homepage/index.js
Labels: feat, refactor, review-required

#12 [2022.10.28] refactor: 데이터 가져오는 플로우 형식 변경
  public/index.html
  src/index.js
  src/layout/ServiceLayOut/index.js
  src/pages/ChannelPage/index.js
  src/pages/Homepage/index.js
  src/util/socketFactory.js
Labels: refactor, review-required
